#ifndef WIRECONTROL_GLOBAL_H
#define WIRECONTROL_GLOBAL_H

#include <QtGlobal>

#if defined(WIRECONTROLPLUGIN_LIBRARY)
#  define WIRECONTROLPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIRECONTROLPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIRECONTROL_GLOBAL_H
